export const images = [
  "src/assets/image/SneakersBlue.png",
  "src/assets/image/SneakersGreen.png",
  "src/assets/image/SneakersRed.png",
  "src/assets/image/SneakersWhite.png",
];
export const imageKrossMap = [
  {
    id: 1,
    name: "Ergonomic Gaming Mouse",
    price: 49,
    oldPrice: null,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 125,
    image: "src/assets/image/SneakersWhite.png",
  },
  {
    id: 2,
    name: "Mechanical Keyboard",
    price: 129,
    oldPrice: 159,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 210,
    image: "src/assets/image/SneakersRed.png",
  },
  {
    id: 3,
    name: "Wireless Gaming Headset",
    price: 89,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 88,
    image: "src/assets/image/SneakersBlue.png",
  },
  {
    id: 4,
    name: "High-Performance CPU Cooler",
    price: 69,
    oldPrice: 79,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 180,
    image: "src/assets/image/SneakersGreen.png",
  },
  {
    id: 5,
    name: "RGB Gaming Mouse Pad",
    price: 29,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 250,
    image: "src/assets/image/SneakersBlue.png",
  },
  {
    id: 6,
    name: "Curved Gaming Monitor",
    price: 349,
    oldPrice: 399,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 92,
    image: "src/assets/image/SneakersGreen.png",
  },
  {
    id: 7,
    name: "Gaming Chair",
    price: 199,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 56,
    image: "src/assets/image/SneakersRed.png",
  },
  {
    id: 8,
    name: "VR Headset",
    price: 449,
    oldPrice: 499,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 120,
    image: "src/assets/image/SneakersWhite.png",
  },
];
export const imageKross = [
  {
    id: 9,
    name: "Ergonomic Gaming Mouse",
    price: 49,
    oldPrice: null,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 125,
    image: "src/assets/image/SneakersWhite.png",
  },
  {
    id: 10,
    name: "Mechanical Keyboard",
    price: 129,
    oldPrice: 159,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 210,
    image: "src/assets/image/SneakersRed.png",
  },
  {
    id: 11,
    name: "Wireless Gaming Headset",
    price: 89,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 88,
    image: "src/assets/image/SneakersBlue.png",
  },
  {
    id: 12,
    name: "High-Performance CPU Cooler",
    price: 69,
    oldPrice: 79,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 180,
    image: "src/assets/image/SneakersGreen.png",
  },
  {
    id: 13,
    name: "RGB Gaming Mouse Pad",
    price: 29,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 250,
    image: "src/assets/image/SneakersBlue.png",
  },
  {
    id: 14,
    name: "Curved Gaming Monitor",
    price: 349,
    oldPrice: 399,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 92,
    image: "src/assets/image/SneakersGreen.png",
  },
  {
    id: 15,
    name: "Gaming Chair",
    price: 199,
    oldPrice: null,
    rating: "src/assets/icons/FiveStars.svg",
    reviews: 56,
    image: "src/assets/image/SneakersRed.png",
  },
  {
    id: 16,
    name: "VR Headset",
    price: 449,
    oldPrice: 499,
    rating: "src/assets/icons/FourStars.svg",
    reviews: 120,
    image: "src/assets/image/SneakersWhite.png",
  },
];
